### ISSUE TITLE
不能兼容ie9啊

### ISSUE THREAD

**Issue by lorenking** [z719725611/vue-upload-web#3]
ie9中报错
![image](https://user-images.githubusercontent.com/12979103/37273662-6fffa692-2615-11e8-9a11-19113fb947f6.png)

**Comment by zbao007** [comment]
过段时间上传个在线demo

**Comment by lorenking** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
感谢回复，貌似ie9上传是没问题的，因为之前是node dev环境，导致上传按钮点击没反应，网上说生产环境就没问题了。  



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    




    在2018年03月14日 17:59，zbao<notifications@github.com> 写道： 


过段时间上传个在线demo

**Comment by wulinxian** [comment]
博主可否这几天上传下demo

**Comment by wulinxian** [comment]
博主可否这几天上传下demo
